[package]
name = "solana-app"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-program = "1.18"
solana-client = "1.18"
solana-sdk = "1.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
